import { createApp } from "vue";
import App from "./App.vue";
import router from "./router/index.js";
import store from "./store";

// scss
import "primevue/resources/primevue.min.css";
import "primeicons/primeicons.css";
import "./assets/styles/layout.scss";
import "./assets/demo/flags/flags.css";

import PrimeVue from "primevue/config";
import AutoComplete from "primevue/autocomplete";
import Accordion from "primevue/accordion";
import AccordionTab from "primevue/accordiontab";
import Avatar from "primevue/avatar";
import AvatarGroup from "primevue/avatargroup";
import Badge from "primevue/badge";
import BadgeDirective from "primevue/badgedirective";
import Button from "primevue/button";
import Breadcrumb from "primevue/breadcrumb";
import Calendar from "primevue/calendar";
import Card from "primevue/card";
import Carousel from "primevue/carousel";
import Chart from "primevue/chart";
import Checkbox from "primevue/checkbox";
import Chip from "primevue/chip";
import Chips from "primevue/chips";
import ColorPicker from "primevue/colorpicker";
import Column from "primevue/column";
import ConfirmDialog from "primevue/confirmdialog";
import ConfirmPopup from "primevue/confirmpopup";
import ConfirmationService from "primevue/confirmationservice";
import ContextMenu from "primevue/contextmenu";
import DataTable from "primevue/datatable";
import DataView from "primevue/dataview";
import DataViewLayoutOptions from "primevue/dataviewlayoutoptions";
import Dialog from "primevue/dialog";
import Divider from "primevue/divider";
import Dropdown from "primevue/dropdown";
import Fieldset from "primevue/fieldset";
import FileUpload from "primevue/fileupload";
import Image from "primevue/image";
import InlineMessage from "primevue/inlinemessage";
import Inplace from "primevue/inplace";
import InputMask from "primevue/inputmask";
import InputNumber from "primevue/inputnumber";
import InputSwitch from "primevue/inputswitch";
import InputText from "primevue/inputtext";
import Knob from "primevue/knob";
import Galleria from "primevue/galleria";
import Listbox from "primevue/listbox";
import MegaMenu from "primevue/megamenu";
import Menu from "primevue/menu";
import Menubar from "primevue/menubar";
import Message from "primevue/message";
import MultiSelect from "primevue/multiselect";
import OrderList from "primevue/orderlist";
import OrganizationChart from "primevue/organizationchart";
import OverlayPanel from "primevue/overlaypanel";
import Paginator from "primevue/paginator";
import Panel from "primevue/panel";
import PanelMenu from "primevue/panelmenu";
import Password from "primevue/password";
import PickList from "primevue/picklist";
import ProgressBar from "primevue/progressbar";
import Rating from "primevue/rating";
import RadioButton from "primevue/radiobutton";
import Ripple from "primevue/ripple";
import SelectButton from "primevue/selectbutton";
import ScrollPanel from "primevue/scrollpanel";
import ScrollTop from "primevue/scrolltop";
import Slider from "primevue/slider";
import Sidebar from "primevue/sidebar";
import Skeleton from "primevue/skeleton";
import SplitButton from "primevue/splitbutton";
import Splitter from "primevue/splitter";
import SplitterPanel from "primevue/splitterpanel";
import Steps from "primevue/steps";
import StyleClass from "primevue/styleclass";
import TabMenu from "primevue/tabmenu";
import Tag from "primevue/tag";
import TieredMenu from "primevue/tieredmenu";
import Textarea from "primevue/textarea";
import Timeline from "primevue/timeline";
import Toast from "primevue/toast";
import ToastService from "primevue/toastservice";
import Toolbar from "primevue/toolbar";
import TabView from "primevue/tabview";
import TabPanel from "primevue/tabpanel";
import Tooltip from "primevue/tooltip";
import ToggleButton from "primevue/togglebutton";
import Tree from "primevue/tree";
import TreeSelect from "primevue/treeselect";
import TreeTable from "primevue/treetable";
import TriStateCheckbox from "primevue/tristatecheckbox";

createApp(App)
  .use(store)
  .use(router)
  .use(PrimeVue, { ripple: true, inputStyle: "outlined" })
  .use(ToastService)
  .use(ConfirmationService)
  .mount("#app");

createApp(App).component("Dialog", Dialog);

createApp(App).directive("tooltip", Tooltip);
createApp(App).directive("ripple", Ripple);
createApp(App).directive("badge", BadgeDirective);
createApp(App).directive("styleclass", StyleClass);

createApp(App).component("Accordion", Accordion);
createApp(App).component("AccordionTab", AccordionTab);
createApp(App).component("AutoComplete", AutoComplete);
createApp(App).component("Avatar", Avatar);
createApp(App).component("AvatarGroup", AvatarGroup);
createApp(App).component("Badge", Badge);
createApp(App).component("Breadcrumb", Breadcrumb);
createApp(App).component("Button", Button);
createApp(App).component("Calendar", Calendar);
createApp(App).component("Card", Card);
createApp(App).component("Carousel", Carousel);
createApp(App).component("Chart", Chart);
createApp(App).component("Checkbox", Checkbox);
createApp(App).component("Chip", Chip);
createApp(App).component("Chips", Chips);
createApp(App).component("ColorPicker", ColorPicker);
createApp(App).component("Column", Column);
createApp(App).component("ConfirmDialog", ConfirmDialog);
createApp(App).component("ConfirmPopup", ConfirmPopup);
createApp(App).component("ContextMenu", ContextMenu);
createApp(App).component("DataTable", DataTable);
createApp(App).component("DataView", DataView);
createApp(App).component("DataViewLayoutOptions", DataViewLayoutOptions);
createApp(App).component("Dialog", Dialog);
createApp(App).component("Divider", Divider);
createApp(App).component("Dropdown", Dropdown);
createApp(App).component("Fieldset", Fieldset);
createApp(App).component("FileUpload", FileUpload);
createApp(App).component("Image", Image);
createApp(App).component("InlineMessage", InlineMessage);
createApp(App).component("Inplace", Inplace);
createApp(App).component("InputMask", InputMask);
createApp(App).component("InputNumber", InputNumber);
createApp(App).component("InputSwitch", InputSwitch);
createApp(App).component("InputText", InputText);
createApp(App).component("Galleria", Galleria);
createApp(App).component("Knob", Knob);
createApp(App).component("Listbox", Listbox);
createApp(App).component("MegaMenu", MegaMenu);
createApp(App).component("Menu", Menu);
createApp(App).component("Menubar", Menubar);
createApp(App).component("Message", Message);
createApp(App).component("MultiSelect", MultiSelect);
createApp(App).component("OrderList", OrderList);
createApp(App).component("OrganizationChart", OrganizationChart);
createApp(App).component("OverlayPanel", OverlayPanel);
createApp(App).component("Paginator", Paginator);
createApp(App).component("Panel", Panel);
createApp(App).component("PanelMenu", PanelMenu);
createApp(App).component("Password", Password);
createApp(App).component("PickList", PickList);
createApp(App).component("ProgressBar", ProgressBar);
createApp(App).component("RadioButton", RadioButton);
createApp(App).component("Rating", Rating);
createApp(App).component("SelectButton", SelectButton);
createApp(App).component("ScrollPanel", ScrollPanel);
createApp(App).component("ScrollTop", ScrollTop);
createApp(App).component("Slider", Slider);
createApp(App).component("Sidebar", Sidebar);
createApp(App).component("Skeleton", Skeleton);
createApp(App).component("SplitButton", SplitButton);
createApp(App).component("Splitter", Splitter);
createApp(App).component("SplitterPanel", SplitterPanel);
createApp(App).component("Steps", Steps);
createApp(App).component("TabMenu", TabMenu);
createApp(App).component("TabView", TabView);
createApp(App).component("TabPanel", TabPanel);
createApp(App).component("Tag", Tag);
createApp(App).component("Textarea", Textarea);
createApp(App).component("TieredMenu", TieredMenu);
createApp(App).component("Timeline", Timeline);
createApp(App).component("Toast", Toast);
createApp(App).component("Toolbar", Toolbar);
createApp(App).component("ToggleButton", ToggleButton);
createApp(App).component("Tree", Tree);
createApp(App).component("TreeSelect", TreeSelect);
createApp(App).component("TreeTable", TreeTable);
createApp(App).component("TriStateCheckbox", TriStateCheckbox);
